[package]
name = "yupdates"
version = "0.0.1"
edition = "2021"
description = "Yupdates Rust SDK"
readme = "README.md"
homepage = "https://github.com/yupdates/yupdates-sdk-rs/"
repository = "https://github.com/yupdates/yupdates-sdk-rs/"
license = "MIT"

[dependencies]
